server: server
api:
  base: https://junction.at
  ApiKey: 
message:
  banappend:  Appeal:junction.at/appeal
  error: Internal error. Please notify staff.
  noperms: You do not have permission to access this command.
