server: server
api:
  base: https://junction.at
  username: Anathema
  password: password
message:
  banappend: - Appeal: junction.at/appeal
  error: Internal error. Please notify staff.
  notmember: You are not a member.
  
  lookup:
    lookupstart: -------- LOOKUP START --------
    lookupend: --------- LOOKUP END ---------
