name: Anathema
version: 2.0
description: Anathema Ban System
author: junction.at
website: http://git.junction.at/anathema

main: at.junction.anathema.Anathema

commands:
  a: 
    description: Access Anathema
    permission: junction.anathema.access
    usage: /a [ban|rban|addnote|rnote|lookup]
