name: Anathema
main: at.junction.anathema.Anathema
version: 1.0
commands:
  a:
    description: Anathema action command
    permission: junction.anathema.use
    usage: Look in docs.
  c:
    description: Anathema browse command
    permission: junction.anathema.use
    usage: Look in docs.