name: Anathema
version: 2.1
description: Anathema Ban System
author: junction.at
website: http://git.junction.at/anathema

main: at.junction.anathema.Anathema

commands:
  a:
    description: Anathema Main Command
    permission: junction.anathema.access
    usage: /a
  ban:
    description: Ban Player
    permission: junction.anathema.access
    usage: /ban <username> <reason>
  unban:
    description: Unban Player
    permission: junction.anathema.access
    usage: /unban <username>
  addnote:
    description: Add a note to a player's account
    permission: junction.anathema.access
    usage: /addnote <username> <note>
  lookup:
    description: Show bans/notes for a player
    permission: junction.anathema.access
    usage: /lookup <username>
permissions:
  junction.anathema.access:
    description: Allows a player to use anathema
    default: op
